services:
  - type: web
    name: translachat
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: HOST_EMAIL
        sync: false
      - key: HOST_PASSWORD
        sync: false
      - key: HOST_NAME
        sync: false
